package simconnect

//Divers
const (
	MAX_PATH = 260
)

const (
	SIMCONNECT_RECV_ID_NULL                             = iota
	SIMCONNECT_RECV_ID_EXCEPTION                        = iota
	SIMCONNECT_RECV_ID_OPEN                             = iota
	SIMCONNECT_RECV_ID_QUIT                             = iota
	SIMCONNECT_RECV_ID_EVENT                            = iota
	SIMCONNECT_RECV_ID_EVENT_OBJECT_ADDREMOVE           = iota
	SIMCONNECT_RECV_ID_EVENT_FILENAME                   = iota
	SIMCONNECT_RECV_ID_EVENT_FRAME                      = iota
	SIMCONNECT_RECV_ID_SIMOBJECT_DATA                   = iota
	SIMCONNECT_RECV_ID_SIMOBJECT_DATA_BYTYPE            = iota
	SIMCONNECT_RECV_ID_WEATHER_OBSERVATION              = iota
	SIMCONNECT_RECV_ID_CLOUD_STATE                      = iota
	SIMCONNECT_RECV_ID_ASSIGNED_OBJECT_ID               = iota
	SIMCONNECT_RECV_ID_RESERVED_KEY                     = iota
	SIMCONNECT_RECV_ID_CUSTOM_ACTION                    = iota
	SIMCONNECT_RECV_ID_SYSTEM_STATE                     = iota
	SIMCONNECT_RECV_ID_CLIENT_DATA                      = iota
	SIMCONNECT_RECV_ID_EVENT_WEATHER_MODE               = iota
	SIMCONNECT_RECV_ID_AIRPORT_LIST                     = iota
	SIMCONNECT_RECV_ID_VOR_LIST                         = iota
	SIMCONNECT_RECV_ID_NDB_LIST                         = iota
	SIMCONNECT_RECV_ID_WAYPOINT_LIST                    = iota
	SIMCONNECT_RECV_ID_EVENT_MULTIPLAYER_SERVER_STARTED = iota
	SIMCONNECT_RECV_ID_EVENT_MULTIPLAYER_CLIENT_STARTED = iota
	SIMCONNECT_RECV_ID_EVENT_MULTIPLAYER_SESSION_ENDED  = iota
	SIMCONNECT_RECV_ID_EVENT_RACE_END                   = iota
	SIMCONNECT_RECV_ID_EVENT_RACE_LAP                   = iota
)

const (
	SIMCONNECT_DATATYPE_INVALID      = iota
	SIMCONNECT_DATATYPE_INT32        = iota
	SIMCONNECT_DATATYPE_INT64        = iota
	SIMCONNECT_DATATYPE_FLOAT32      = iota
	SIMCONNECT_DATATYPE_FLOAT64      = iota
	SIMCONNECT_DATATYPE_STRING8      = iota
	SIMCONNECT_DATATYPE_STRING32     = iota
	SIMCONNECT_DATATYPE_STRING64     = iota
	SIMCONNECT_DATATYPE_STRING128    = iota
	SIMCONNECT_DATATYPE_STRING256    = iota
	SIMCONNECT_DATATYPE_STRING260    = iota
	SIMCONNECT_DATATYPE_STRINGV      = iota
	SIMCONNECT_DATATYPE_INITPOSITION = iota
	SIMCONNECT_DATATYPE_MARKERSTATE  = iota
	SIMCONNECT_DATATYPE_WAYPOINT     = iota
	SIMCONNECT_DATATYPE_LATLONALT    = iota
	SIMCONNECT_DATATYPE_XYZ          = iota

	SIMCONNECT_DATATYPE_MAX = iota
)
const (
	SIMCONNECT_EXCEPTION_NONE = iota

	SIMCONNECT_EXCEPTION_ERROR                             = iota
	SIMCONNECT_EXCEPTION_SIZE_MISMATCH                     = iota
	SIMCONNECT_EXCEPTION_UNRECOGNIZED_ID                   = iota
	SIMCONNECT_EXCEPTION_UNOPENED                          = iota
	SIMCONNECT_EXCEPTION_VERSION_MISMATCH                  = iota
	SIMCONNECT_EXCEPTION_TOO_MANY_GROUPS                   = iota
	SIMCONNECT_EXCEPTION_NAME_UNRECOGNIZED                 = iota
	SIMCONNECT_EXCEPTION_TOO_MANY_EVENT_NAMES              = iota
	SIMCONNECT_EXCEPTION_EVENT_ID_DUPLICATE                = iota
	SIMCONNECT_EXCEPTION_TOO_MANY_MAPS                     = iota
	SIMCONNECT_EXCEPTION_TOO_MANY_OBJECTS                  = iota
	SIMCONNECT_EXCEPTION_TOO_MANY_REQUESTS                 = iota
	SIMCONNECT_EXCEPTION_WEATHER_INVALID_PORT              = iota
	SIMCONNECT_EXCEPTION_WEATHER_INVALID_METAR             = iota
	SIMCONNECT_EXCEPTION_WEATHER_UNABLE_TO_GET_OBSERVATION = iota
	SIMCONNECT_EXCEPTION_WEATHER_UNABLE_TO_CREATE_STATION  = iota
	SIMCONNECT_EXCEPTION_WEATHER_UNABLE_TO_REMOVE_STATION  = iota
	SIMCONNECT_EXCEPTION_INVALID_DATA_TYPE                 = iota
	SIMCONNECT_EXCEPTION_INVALID_DATA_SIZE                 = iota
	SIMCONNECT_EXCEPTION_DATA_ERROR                        = iota
	SIMCONNECT_EXCEPTION_INVALID_ARRAY                     = iota
	SIMCONNECT_EXCEPTION_CREATE_OBJECT_FAILED              = iota
	SIMCONNECT_EXCEPTION_LOAD_FLIGHTPLAN_FAILED            = iota
	SIMCONNECT_EXCEPTION_OPERATION_INVALID_FOR_OBJECT_TYPE = iota
	SIMCONNECT_EXCEPTION_ILLEGAL_OPERATION                 = iota
	SIMCONNECT_EXCEPTION_ALREADY_SUBSCRIBED                = iota
	SIMCONNECT_EXCEPTION_INVALID_ENUM                      = iota
	SIMCONNECT_EXCEPTION_DEFINITION_ERROR                  = iota
	SIMCONNECT_EXCEPTION_DUPLICATE_ID                      = iota
	SIMCONNECT_EXCEPTION_DATUM_ID                          = iota
	SIMCONNECT_EXCEPTION_OUT_OF_BOUNDS                     = iota
	SIMCONNECT_EXCEPTION_ALREADY_CREATED                   = iota
	SIMCONNECT_EXCEPTION_OBJECT_OUTSIDE_REALITY_BUBBLE     = iota
	SIMCONNECT_EXCEPTION_OBJECT_CONTAINER                  = iota
	SIMCONNECT_EXCEPTION_OBJECT_AI                         = iota
	SIMCONNECT_EXCEPTION_OBJECT_ATC                        = iota
	SIMCONNECT_EXCEPTION_OBJECT_SCHEDULE                   = iota
)

const (
	SIMCONNECT_SIMOBJECT_TYPE_USER       = iota
	SIMCONNECT_SIMOBJECT_TYPE_ALL        = iota
	SIMCONNECT_SIMOBJECT_TYPE_AIRCRAFT   = iota
	SIMCONNECT_SIMOBJECT_TYPE_HELICOPTER = iota
	SIMCONNECT_SIMOBJECT_TYPE_BOAT       = iota
	SIMCONNECT_SIMOBJECT_TYPE_GROUND     = iota
)

const (
	SIMCONNECT_STATE_OFF = iota
	SIMCONNECT_STATE_ON  = iota
)

const (
	SIMCONNECT_PERIOD_NEVER        = iota
	SIMCONNECT_PERIOD_ONCE         = iota
	SIMCONNECT_PERIOD_VISUAL_FRAME = iota
	SIMCONNECT_PERIOD_SIM_FRAME    = iota
	SIMCONNECT_PERIOD_SECOND       = iota
)

const (
	SIMCONNECT_MISSION_FAILED    = iota
	SIMCONNECT_MISSION_CRASHED   = iota
	SIMCONNECT_MISSION_SUCCEEDED = iota
)

const (
	SIMCONNECT_CLIENT_DATA_PERIOD_NEVER        = iota
	SIMCONNECT_CLIENT_DATA_PERIOD_ONCE         = iota
	SIMCONNECT_CLIENT_DATA_PERIOD_VISUAL_FRAME = iota
	SIMCONNECT_CLIENT_DATA_PERIOD_ON_SET       = iota
	SIMCONNECT_CLIENT_DATA_PERIOD_SECOND       = iota
)
const (
	SIMCONNECT_TEXT_TYPE_SCROLL_BLACK   = iota
	SIMCONNECT_TEXT_TYPE_SCROLL_WHITE   = iota
	SIMCONNECT_TEXT_TYPE_SCROLL_RED     = iota
	SIMCONNECT_TEXT_TYPE_SCROLL_GREEN   = iota
	SIMCONNECT_TEXT_TYPE_SCROLL_BLUE    = iota
	SIMCONNECT_TEXT_TYPE_SCROLL_YELLOW  = iota
	SIMCONNECT_TEXT_TYPE_SCROLL_MAGENTA = iota
	SIMCONNECT_TEXT_TYPE_SCROLL_CYAN    = iota
	SIMCONNECT_TEXT_TYPE_PRINT_BLACK    = 0x0100
	SIMCONNECT_TEXT_TYPE_PRINT_WHITE    = SIMCONNECT_TEXT_TYPE_PRINT_BLACK + 0x1
	SIMCONNECT_TEXT_TYPE_PRINT_RED      = SIMCONNECT_TEXT_TYPE_PRINT_WHITE + 0x1
	SIMCONNECT_TEXT_TYPE_PRINT_GREEN    = SIMCONNECT_TEXT_TYPE_PRINT_RED + 0x1
	SIMCONNECT_TEXT_TYPE_PRINT_BLUE     = SIMCONNECT_TEXT_TYPE_PRINT_GREEN + 0x1
	SIMCONNECT_TEXT_TYPE_PRINT_YELLOW   = SIMCONNECT_TEXT_TYPE_PRINT_BLUE + 0x1
	SIMCONNECT_TEXT_TYPE_PRINT_MAGENTA  = SIMCONNECT_TEXT_TYPE_PRINT_YELLOW + 0x1
	SIMCONNECT_TEXT_TYPE_PRINT_CYAN     = SIMCONNECT_TEXT_TYPE_PRINT_MAGENTA + 0x1
	SIMCONNECT_TEXT_TYPE_MENU           = 0x0200
)

const (
	SIMCONNECT_TEXT_RESULT_MENU_SELECT_1  = iota
	SIMCONNECT_TEXT_RESULT_MENU_SELECT_2  = iota
	SIMCONNECT_TEXT_RESULT_MENU_SELECT_3  = iota
	SIMCONNECT_TEXT_RESULT_MENU_SELECT_4  = iota
	SIMCONNECT_TEXT_RESULT_MENU_SELECT_5  = iota
	SIMCONNECT_TEXT_RESULT_MENU_SELECT_6  = iota
	SIMCONNECT_TEXT_RESULT_MENU_SELECT_7  = iota
	SIMCONNECT_TEXT_RESULT_MENU_SELECT_8  = iota
	SIMCONNECT_TEXT_RESULT_MENU_SELECT_9  = iota
	SIMCONNECT_TEXT_RESULT_MENU_SELECT_10 = iota
	SIMCONNECT_TEXT_RESULT_DISPLAYED      = 0x00010000
	SIMCONNECT_TEXT_RESULT_QUEUED         = SIMCONNECT_TEXT_RESULT_DISPLAYED + 0x1
	SIMCONNECT_TEXT_RESULT_REMOVED        = SIMCONNECT_TEXT_RESULT_QUEUED + 0x1
	SIMCONNECT_TEXT_RESULT_REPLACED       = SIMCONNECT_TEXT_RESULT_REMOVED + 0x1
	SIMCONNECT_TEXT_RESULT_TIMEOUT        = SIMCONNECT_TEXT_RESULT_REPLACED + 0x1
)

const (
	SIMCONNECT_WEATHER_MODE_THEME  = iota
	SIMCONNECT_WEATHER_MODE_RWW    = iota
	SIMCONNECT_WEATHER_MODE_CUSTOM = iota
	SIMCONNECT_WEATHER_MODE_GLOBAL = iota
)

const (
	SIMCONNECT_FACILITY_LIST_TYPE_AIRPORT  = iota
	SIMCONNECT_FACILITY_LIST_TYPE_WAYPOINT = iota
	SIMCONNECT_FACILITY_LIST_TYPE_NDB      = iota
	SIMCONNECT_FACILITY_LIST_TYPE_VOR      = iota
	SIMCONNECT_FACILITY_LIST_TYPE_COUNT    = iota // invalid
)

// SIMCONNECT_VOR_FLAGS flags for SIMCONNECT_RECV_ID_VOR_LIST
const (
	SIMCONNECT_RECV_ID_VOR_LIST_HAS_NAV_SIGNAL  = 0x00000001 // Has Nav signal
	SIMCONNECT_RECV_ID_VOR_LIST_HAS_LOCALIZER   = 0x00000002 // Has localizer
	SIMCONNECT_RECV_ID_VOR_LIST_HAS_GLIDE_SLOPE = 0x00000004 // Has Nav signal
	SIMCONNECT_RECV_ID_VOR_LIST_HAS_DME         = 0x00000008 // Station has DME
)

// SIMCONNECT_WAYPOINT_FLAGS bits for the Waypoint Flags field: may be combined
const (
	SIMCONNECT_WAYPOINT_NONE                   = 0x00
	SIMCONNECT_WAYPOINT_SPEED_REQUESTED        = 0x04       // requested speed at waypoint is valid
	SIMCONNECT_WAYPOINT_THROTTLE_REQUESTED     = 0x08       // request a specific throttle percentage
	SIMCONNECT_WAYPOINT_COMPUTE_VERTICAL_SPEED = 0x10       // compute vertical to speed to reach waypoint altitude when crossing the waypoint
	SIMCONNECT_WAYPOINT_ALTITUDE_IS_AGL        = 0x20       // AltitudeIsAGL
	SIMCONNECT_WAYPOINT_ON_GROUND              = 0x00100000 // place this waypoint on the ground
	SIMCONNECT_WAYPOINT_REVERSE                = 0x00200000 // Back up to this waypoint. Only valid on first waypoint
	SIMCONNECT_WAYPOINT_WRAP_TO_FIRST          = 0x00400000 // Wrap around back to first waypoint. Only valid on last waypoint.
)

// SIMCONNECT_EVENT_FLAG
const (
	SIMCONNECT_EVENT_FLAG_DEFAULT             = 0x00000000
	SIMCONNECT_EVENT_FLAG_FAST_REPEAT_TIMER   = 0x00000001 // set event repeat timer to simulate fast repeat
	SIMCONNECT_EVENT_FLAG_SLOW_REPEAT_TIMER   = 0x00000002 // set event repeat timer to simulate slow repeat
	SIMCONNECT_EVENT_FLAG_GROUPID_IS_PRIORITY = 0x00000010 // interpret GroupID parameter as priority value
)

// SIMCONNECT_DATA_REQUEST_FLAG
const (
	SIMCONNECT_DATA_REQUEST_FLAG_DEFAULT = 0x00000000
	SIMCONNECT_DATA_REQUEST_FLAG_CHANGED = 0x00000001 // send requested data when value(s) change
	SIMCONNECT_DATA_REQUEST_FLAG_TAGGED  = 0x00000002 // send requested data in tagged format
)

// SIMCONNECT_DATA_SET_FLAG
const (
	SIMCONNECT_DATA_SET_FLAG_DEFAULT = 0x00000000
	SIMCONNECT_DATA_SET_FLAG_TAGGED  = 0x00000001 // data is in tagged format
)

// SIMCONNECT_CREATE_CLIENT_DATA_FLAG
const (
	SIMCONNECT_CREATE_CLIENT_DATA_FLAG_DEFAULT   = 0x00000000
	SIMCONNECT_CREATE_CLIENT_DATA_FLAG_READ_ONLY = 0x00000001 // permit only ClientData creator to write into ClientData
)

// SIMCONNECT_CLIENT_DATA_REQUEST_FLAG
const (
	SIMCONNECT_CLIENT_DATA_REQUEST_FLAG_DEFAULT = 0x00000000
	SIMCONNECT_CLIENT_DATA_REQUEST_FLAG_CHANGED = 0x00000001 // send requested ClientData when value(s) change
	SIMCONNECT_CLIENT_DATA_REQUEST_FLAG_TAGGED  = 0x00000002 // send requested ClientData in tagged format
)

// SIMCONNECT_CLIENT_DATA_SET_FLAG
const (
	SIMCONNECT_CLIENT_DATA_SET_FLAG_DEFAULT = 0x00000000
	SIMCONNECT_CLIENT_DATA_SET_FLAG_TAGGED  = 0x00000001 // data is in tagged format
)

// SIMCONNECT_VIEW_SYSTEM_EVENT_DATA dwData contains these flags for the "View" System Event
const (
	SIMCONNECT_VIEW_SYSTEM_EVENT_DATA_COCKPIT_2D      = 0x00000001 // 2D Panels in cockpit view
	SIMCONNECT_VIEW_SYSTEM_EVENT_DATA_COCKPIT_VIRTUAL = 0x00000002 // Virtual (3D) panels in cockpit view
	SIMCONNECT_VIEW_SYSTEM_EVENT_DATA_ORTHOGONAL      = 0x00000004 // Orthogonal (Map) view
)

// SIMCONNECT_SOUND_SYSTEM_EVENT_DATA dwData contains these flags for the "Sound" System Event
const (
	SIMCONNECT_SOUND_SYSTEM_EVENT_DATA_MASTER = 0x00000001 // Sound Master
)
